Created Use Case document
jakeharding/repo-health pull request #39
Opened 2017-03-29 20:45 UTC by bparish628

This includes our use case of allowing a project lead to determine what libraries to use within the project.

2017-03-29 23:38 UTC, jakeharding requested changes
A few misspellings and some punctuation consistency.

2017-03-29 23:38 UTC, jakeharding commented on docs/Use Case.md
> +**Goal in Context:** The project lead is able to access if an open source project is healthly enough for its company's standards to incorporate into their product.
Is `access` supposed to be `assess`?

2017-03-29 23:38 UTC, jakeharding commented on docs/Use Case.md
> +* Project Lead: To understand if software is apporiate to incorporate into their own product
Misspelling of appropriate.

2017-03-29 23:38 UTC, jakeharding commented on docs/Use Case.md
> +* Manager: To access the longevity of this project with regards to dependencies
access == assess?

2017-03-29 23:38 UTC, jakeharding commented on docs/Use Case.md
> +**Failed End Conditions:** Project lead recieves little to no information on the health of the chosen repository.
Misspelling of receives.

2017-03-29 23:38 UTC, jakeharding commented on docs/Use Case.md
> +**Main Success Scenario:** Project lead understands the metrics presented and makes an accurate decision on if the software should be incoporated
I suggest removing the word on between decision and if.

2017-03-29 23:38 UTC, jakeharding commented on docs/Use Case.md
> +**Failed End Conditions:** Project lead recieves little to no information on the health of the chosen repository.
Nitpick: Some of these are bullets and some are sentences. Consistently use periods at the end of the sentences and bullets can go either way as long as they are consistent.

2017-03-29 23:38 UTC, jakeharding commented on docs/Use Case.md
> +**Trigger:** Project lead is assigned to a brand new project and needs to access what libraries and dependencies should be used
access == assess?

2017-03-29 23:40 UTC, bparish628 commented
Well shoot. That's a lot. I really wish it showed me misspellings :cry:

2017-03-30 00:26 UTC, jakeharding approved these changes

2017-03-30 00:46 UTC, merged